title: Kagiso Docs
description: Infrastructure, Helm charts, and platform documentation

remote_theme: just-the-docs/just-the-docs
baseurl: "/just-the-docs"

search_enabled: true

plugins:
  - jekyll-remote-theme

just_the_docs:
  custom_css:
    - assets/css/custom.css
